package com.desapabandara.pos.preference

const val AUTH_TOKEN_KEY = "AUTH_TOKEN_KEY"
const val AUTH_REFRESH_TOKEN_KEY = "AUTH_REFRESH_TOKEN_KEY"
const val AUTH_LOGGED_IN_STORE = "AUTH_LOGGED_IN_STORE"

const val SYNC_STATUS_KEY = "SYNC_STATUS_KEY"

const val LAST_ORDER_NUMBER_KEY = "CURRENT_ORDER_NUMBER_KEY"
const val ORDER_START_DATE_KEY = "ORDER_START_DATE_KEY"
const val LAST_ORDER_SYNC = "LAST_ORDER_SYNC"
